FROM python:3.13.11-alpine3.23 AS builder

WORKDIR /app
COPY requirements_docs.txt .

RUN pip install --requirement requirements_docs.txt

COPY . .

RUN mkdocs build

FROM nginx:1.31.3 AS runtime

COPY --from=builder /app/site /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
