---
apiVersion: v1
kind: Secret
metadata:
  name: library-api-secret
  namespace: library-api
stringData:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/postgres
  JWT_SECRET_KEY: ixBt0XbFQcajKPylO0p4708bIexMXH2VSIpLTDBzxSsEPDuumdzgQCVlhOpeFQ8O
