apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "library-api.fullname" . }}-migrations
  labels:
    {{- include "library-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    spec:
      containers:
      - name: alembic-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
        - /bin/sh
        - -c
        - |
          poetry run alembic upgrade head
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Never
