apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-api.fullname" . }}-mkdocs
  labels:
    {{- include "library-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "library-api-mkdocs.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
